#!/bin/sh

set -e

lb config noauto \
     --distribution bookworm \
     --archive-areas "main contrib non-free non-free-firmware" \
     --bootappend-live "boot=live toram=filesystem.squashfs components locales=en_US.UTF-8 hostname=bahnhof username=hackerman user-fullname=hackerman timezone=Europe/Stockholm persistence persistence-encryption=luks persistence-media=removable-usb keyboard-layouts=se" \
     --mirror-bootstrap http://mirror.zetup.net/debian/ \
     --mirror-binary http://mirror.zetup.net/debian/ \
     "${@}"

